### ISSUE TITLE
An error occurs when you call the Generate

### ISSUE THREAD

**Issue by maxlord** [nvinayshetty/DTOnator#1]
Details in EventLog: 

11:10:06 PluginException: cannot create class "com.nvinayshetty.DTOnator.ActionListener.UserActionListener" [Plugin: com.nvinayshetty.DTOnator]
11:10:23 Throwable: Null child action in group Generate () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=ActionListener

Version: V0.44

**Comment by nvinayshetty** [comment]
Thank you for reporting the issue,
Please make sure that the installation is successful, try uninstalling the plugin->restart->Re install the plugin

From a bit of goggling I found that the same issue exist in some other plugins also, as reported here
https://github.com/jaumard/intellij-sails-ide/issues/1
I'm not quite sure  what is causing the problem..Will fix this issue as soon as possible

with regards,
DTOnator

**Comment by maxlord** [comment]
I tried.
Same problem.

21:41:51 PluginException: cannot create class "i18nHelper" [Plugin: i18n Android Helper]
21:41:59 PluginException: cannot create class "com.nvinayshetty.DTOnator.ActionListener.UserActionListener" [Plugin: com.nvinayshetty.DTOnator]
21:42:23 Throwable: Null child action in group Generate () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=ActionListener

OS: Mac OS X 10.10.4

Android Studio: 1.3.1

**Comment by nvinayshetty** [comment]
Are you facing  the same problem for other plugins Also? From the provided log I can see the same problem in i18nHelper

**Comment by maxlord** [comment]
Yes, i installed few plugins.

The problem is present for some plugins.

**Comment by nvinayshetty** [comment]
fixed in the latest version
