### ISSUE TITLE
Bug: Can't generator Java classes if json array in item is null 

### ISSUE THREAD

**Issue by sonvp** [nvinayshetty/DTOnator#11]
Hi guy . I tested it with my json .It output error 
DTO generator threw an uncaught IncorrectOperationException. Disable Plugin
IncorrectOperationException
           Incorrect field ' '
This is my json
{
  "out_message": "OK",
  "result_data": {
    "data": [
      {

```
    "total_like": 0,
    "video_path": "",
    "map_url": "",
    "avatar": "avatar.png",
    "user_name": "son vo",
    "post": " posted",
    "created_date": "02:50:59 PM",
    "is_Edit": false,
    "count_like": 1,
    "comment": [

    ]
  }
]
```

  }
}

I tested my json with http://jsonutils.com/ and http://jsonviewer.stack.hu/ . It is good .

**Comment by nvinayshetty** [comment]
Fix is available in pre-release version available here
https://github.com/nvinayshetty/DTOnator/releases/tag/0.99
