### ISSUE TITLE
Support generation without @SerializedName

### ISSUE THREAD

**Issue by SpicyCactuar** [nvinayshetty/DTOnator#14]
It's particularly useful, for example, when combining `Retrofit` with `GSON` and using snake case policy for serialization/deserialization.

I know it couples the names of the fields with API JSON names, but as long as it keeps being a conscious decision, it can live with it in order to not pollute the POJO class.

**Comment by nvinayshetty** [comment]
This is already supported. Please select type as Pojo from  right panel instead of the default Gson which is checked by default.

**Comment by SpicyCactuar** [comment]
Lovely, Thanks!
