### ISSUE TITLE
Bug: Get object parameter incorrect from string json

### ISSUE THREAD

**Issue by sonvp** [nvinayshetty/DTOnator#15]
Hi @nvinayshetty  . I tested it with my json

```
{
  "ongoing": {
    "frequency": "123",
    "weekTime": [
      [
        "Week 1 Wed 10:00am-12:00pm"
      ],
      [
        "Week 2 Thu 07:30am-09:30am"
      ]
    ]
  }
}
```
And I receive object key weekTime incorrect. And I tested my json with http://jsonutils.com/, It work well

**Comment by nvinayshetty** [comment]
Fix is available in pre-release version available here
https://github.com/nvinayshetty/DTOnator/releases/tag/0.99
