### ISSUE TITLE
ubuntu it appears blank screen 

### ISSUE THREAD

**Issue by vandanabpatel** [nvinayshetty/DTOnator#19]
DTO plugin not working properly in ubuntu while first time i generate properly then again i tried to genetare from right click -> alt + insert choose DTO  from JSON it appear blank screen in ubuntu.

**Comment by nvinayshetty** [comment]
which version of android studio  you are using?

**Comment by vandanabpatel** [comment]
Android studio 3.0.1

**Comment by nvinayshetty** [comment]
A big release is waiting around the corner I hope it will fix the issue

**Comment by nvinayshetty** [comment]
I made a pre-release for the next version available here
[https://github.com/nvinayshetty/DTOnator/releases/tag/0.99](url)
please let me know if that fixes the issue
