### ISSUE TITLE
Bug. Generate abstract classes

### ISSUE THREAD

**Issue by alexeymorozua** [nvinayshetty/DTOnator#20]
public abstract class SystemRegisterRequest {
  @SerializedName("pin") private String mPin;
  @SerializedName("phone") private String mPhone;
}

**Comment by nvinayshetty** [comment]
Thank you very much for reporting. I removed the latest release from jetbrains and uploaded another build with the fix, The update should be available within 2 days.
You can access the build with fixes via this url 
 https://plugins.jetbrains.com/plugin/7834-dto-generator/update/42598

Regards,
Vinay
