### ISSUE TITLE
Problem loading plugin

### ISSUE THREAD

**Issue by jamesarich** [nvinayshetty/DTOnator#3]
12:02:48 PM PluginException: cannot create class "com.nvinayshetty.DTOnator.ActionListener.UserActionListener" [Plugin: com.nvinayshetty.DTOnator]

Android Studio 1.4 Beta 4

**Comment by nvinayshetty** [comment]
fixed in the version V0.48

**Comment by TrungVuHD** [comment]
I got the same happen on V0.49
I am using android studio 2.1.3 on Mac OSX 10.11.6

Plugin Error: DTO generator threw an uncaught PluginException. Disable Plugin
PluginException: cannot create class "com.nvinayshetty.DTOnator.ActionListener.UserActionListener" [Plugin: com.nvinayshetty.DTOnator]
