### ISSUE TITLE
Unable to use due to uncaught PluginException

### ISSUE THREAD

**Issue by trevor-e** [nvinayshetty/DTOnator#9]
I'm trying to use this plugin (v 0.48) with the latest Android Studio version (2.0 beta6) and it throws a PluginException every time at launch.  I'd love to give more info but I'm not sure where the stacktrace is recorded.

**Comment by nvinayshetty** [comment]
Fix is available in pre-release version available here
https://github.com/nvinayshetty/DTOnator/releases/tag/0.99
